import{a as w,S as v,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const P="51566041-17ae6664d6c49a5767f7403ab",S="https://pixabay.com/api/",R=15;async function u(o,r=1){const s=new URLSearchParams({key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:R,page:r});return(await w.get(`${S}?${s}`)).data}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const r=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:t,views:c,comments:b,downloads:L})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${i}">
            <img src="${s}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${t}</p>
            <p><b>Views:</b> ${c}</p>
            <p><b>Comments:</b> ${b}</p>
            <p><b>Downloads:</b> ${L}</p>
          </div>
        </li>
      `).join("");p.insertAdjacentHTML("beforeend",r),q.refresh()}function $(){p.innerHTML=""}function g(){f.classList.add("visible")}function y(){f.classList.remove("visible")}const E=document.querySelector(".form"),l=document.querySelector(".load-more-btn");let n=1,d="";const h=15;E.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){a.warning({message:"Please enter a search term.",position:"topRight"});return}d=r,n=1,$(),l.classList.add("hidden"),g();try{const{hits:s,totalHits:i}=await u(d,n);if(s.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(s);const e=document.querySelector(".gallery-item");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}n*h>=i?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):l.classList.remove("hidden")}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});l.addEventListener("click",async()=>{n+=1,g();try{const{hits:o,totalHits:r}=await u(d,n);m(o),n*h>=r&&(l.classList.add("hidden"),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
