import{a as P,S as v,i as n}from"./assets/vendor-5YrzWRhu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const S="51566041-17ae6664d6c49a5767f7403ab",q="https://pixabay.com/api/",u=15;async function f(r,o=1){const s=new URLSearchParams({key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:u,page:o});return(await P.get(`${q}?${s}`)).data}const y=document.querySelector(".gallery"),p=document.querySelector(".loader"),i=document.querySelector(".load-more-btn"),R=new v(".gallery a",{captionsData:"alt",captionDelay:250});function m(r){const o=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:t,views:l,comments:L,downloads:w})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${a}">
            <img src="${s}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${t}</p>
            <p><b>Views</b> ${l}</p>
            <p><b>Comments</b> ${L}</p>
            <p><b>Downloads</b> ${w}</p>
          </div>
        </li>
      `).join("");y.insertAdjacentHTML("beforeend",o),R.refresh()}function $(){y.innerHTML=""}function h(){p.classList.add("visible")}function b(){p.classList.remove("visible")}function M(){i.classList.remove("hidden"),i.disabled=!1,i.style.opacity="1"}function d(){i.classList.add("hidden")}function E(){i.disabled=!0,i.style.opacity="0.5"}function B(){i.disabled=!1,i.style.opacity="1"}const O=document.querySelector(".form"),x=document.querySelector(".load-more-btn");let c=1,g="";O.addEventListener("submit",async r=>{r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(!o){n.warning({message:"Please enter a search term.",position:"topRight"});return}g=o,c=1,$(),d(),h();try{const{hits:s,totalHits:a}=await f(g,c);if(s.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(s),s.length<u||c*u>=a?(n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d()):M()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),d()}finally{b()}});x.addEventListener("click",async()=>{c+=1,E(),h();try{const{hits:r,totalHits:o}=await f(g,c);m(r),r.length<u||c*u>=o?(n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d()):B();const{height:a}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),d()}finally{b()}});
//# sourceMappingURL=index.js.map
